# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ming-Dao Chia
tagline:          ''
description:      'Biologist. Designer. Engineer. Coder. Maker.'
url:              https://mingdaochia.com/
baseurl:          /

author:
  name:           'Ming-Dao Chia'
  url:            https://mingdaochia.com/

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/mdchia/hyde-website/
