# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ming-Dao Chia
tagline:          'Building a better tomorrow'
description:      'Biologist. Designer. Maker.'
url:              https://mingdaochia.com

author:
  name:           'Ming-Dao Chia'
  url:            https://mingdaochia.com

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/mdchia/hyde-website/
