# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ming-Dao Chia
tagline:          ''
description:      'Biologist. Designer. Engineer. Coder. Maker.'
url:              https://mdchia.github.io/hyde-website/
baseurl:          /

author:
  name:           'Ming-Dao Chia'
  url:            https://mdchia.github.io/hyde-website/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mdchia/hyde-website/
